import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute w-screen z-20">
          <Navbar />
        </nav>
        <main className="min-h-screen min-w-screen dark:bg-gradient-to-r from-[#222558] to-[#202136]">
          {children}
        </main>
      </body>
    </html>
  );
}
